import type { CarbonTechnology } from "./types";
import { MATURITY_LEVEL, SOURCE_TYPE } from "./constants";

/** 模拟减排技术数据 */
export const MOCK_TECHNOLOGIES: CarbonTechnology[] = [
  {
    tech_id: "1",
    tech_name: "蓄热式加热炉改造",
    industry_code: ["C31", "C32"],
    applicable_process: "轧钢加热环节",
    reduction_potential: "减少燃气消耗约20%",
    maturity_level: MATURITY_LEVEL.COMMERCIAL,
    investment_cost: "200-500万元",
    payback_period: "2-3年",
    source_type: SOURCE_TYPE.GOVERNMENT,
    source_name: "钢铁行业节能减排技术推广目录",
    source_url: "https://example.com/doc1",
    source_year: 2023,
  },
  {
    tech_id: "2",
    tech_name: "余热余压回收利用",
    industry_code: ["C31", "C25"],
    applicable_process: "高炉、转炉烟气",
    reduction_potential: "节能15%-25%",
    maturity_level: MATURITY_LEVEL.COMMERCIAL,
    investment_cost: "500-2000万元",
    payback_period: "3-5年",
    source_type: SOURCE_TYPE.ASSOCIATION,
    source_name: "中国钢铁工业协会技术指南",
    source_year: 2022,
  },
  {
    tech_id: "3",
    tech_name: "氢基直接还原铁技术",
    industry_code: ["C31"],
    applicable_process: "炼铁环节替代高炉",
    reduction_potential: "CO2减排50%以上",
    maturity_level: MATURITY_LEVEL.PILOT,
    investment_cost: "高",
    source_type: SOURCE_TYPE.PAPER,
    source_name: "低碳炼铁技术路线图研究报告",
    source_year: 2024,
  },
  {
    tech_id: "4",
    tech_name: "碳捕集与封存(CCUS)",
    industry_code: ["C31", "C25", "D44"],
    applicable_process: "烟气处理",
    reduction_potential: "CO2捕集率90%",
    maturity_level: MATURITY_LEVEL.RD,
    investment_cost: "待评估",
    source_type: SOURCE_TYPE.GOVERNMENT,
    source_name: "CCUS技术发展路线图",
    source_year: 2023,
  },
  {
    tech_id: "5",
    tech_name: "电炉短流程炼钢",
    industry_code: ["C31", "C33"],
    applicable_process: "废钢冶炼",
    reduction_potential: "吨钢CO2排放降低约60%",
    maturity_level: MATURITY_LEVEL.COMMERCIAL,
    investment_cost: "1000-5000万元",
    payback_period: "5-8年",
    source_type: SOURCE_TYPE.ENTERPRISE,
    source_name: "某钢企电炉改造案例",
    source_year: 2022,
  },
];
